name: Build and Test React Application

on :
  push:
    branches: [ main/main ]
  pull_request:
    branches: [ main/main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses : actions/checkout@v3
    - run : 